### ISSUE TITLE
Odd behaviour on Windows

### ISSUE THREAD

**Issue by avalon60** [Akascape/CTkMessagebox#22]
Hi @Akascape. I am using CTkMessageBox (2.0) on my DCCM app, and I just noticed something odd when I am running on Windows.

On Linux it appears like this:

![image](https://github.com/Akascape/CTkMessagebox/assets/89534395/dacf561a-a583-47ae-a55a-eaf9767fcde3)

As you can see, the above looks quite normal. 

However, when I run this on Windows, I get this:

![MessageBox1](https://github.com/Akascape/CTkMessagebox/assets/89534395/648217fa-63c5-4634-844f-8d84da49e98d)

The central region appears to be set to transparent. Here we can see that it's more obvious what's going on:

![MessageBox2](https://github.com/Akascape/CTkMessagebox/assets/89534395/e231f11d-4f22-40eb-afb6-ba3acc56b3f9)

Here is the API call:

```
                confirm = CTkMessagebox(master=self.root_win,
                                        title='Action Required',
                                        message=f"Database server, {hostname} ({ip}), cannot be reached on port "
                                                f"{port_number}. The connection may require ssh tunnel, VPN etc, "
                                                f"to be established.",
                                        option_1='OK')
```

 Thanks,

Clive

**Comment by Akascape** [comment]
@avalon60 Probably due to the color. The background toplevel color is set as the transparent color for windows, and in your theme the top frame color is also the same. So, you have to change the fg_color of ctkmessagebox to something else. I will try to change this behavior in the next update probably.

**Comment by avalon60** [comment]
So, you deliberately set it transparent on Windows, in the CTkMessagebox code?

**Comment by Akascape** [comment]
@avalon60 Yes, because the method to apply transparency in the corners is different for mac and windows. In windows, we set a transparent color, in mac we have a color called "SystemTransparent", on linux we don't have any transparent attribute and that is why it has only sharp corners. See https://github.com/Akascape/CTkMessagebox/issues/1

**Comment by avalon60** [comment]
OK, so I am trying to understand better, why this only impacts certain themes (I have just tested several). 

It also gets unpredictable. Some of my themes work OK, with others it's the top and bottom horizontal bands which are impacted, becoming transparent, rather than the message text region as previously demonstrated. 

All in all, I think I'd prefer square corners.

**Comment by Akascape** [comment]
@avalon60 > It also gets unpredictable. Some of my themes work OK, with others it's the top and bottom horizontal bands which are impacted, ...

The fg color of toplevel from the theme is set as the trasparent color. The top_fg_color of CTkFrame is set as the color for the middle frame. If both the colors are same then it will show this odd behaviour.

**Comment by avalon60** [comment]
Why don't you simply use CTkFrame.fg_color for one and CTkFrame.top_fg_color the other? Either that or take one of them from CTk.fg_color? 

Not sure why you closed this - surely this is an issue until solved?

**Comment by Akascape** [comment]
@avalon60 
>Why don't you simply use CTkFrame.fg_color for one and CTkFrame.top_fg_color the other? 

That's exactly what the ctkmessagebox use. However, the issue is fixed now.

Let me explain this.
Transparent color set as = CTkToplevel.fg_color (if you use this color then the portion will become transparent)
fg_color of ctkmessagebox = CTkFrame.fg_color 
bg_color of ctkmessagebox = CTkFrame.top_fg_color

if fg_color or bg_color == CTkToplevel fg_color, then it will also become transparent.

**Comment by avalon60** [comment]
Thanks - the fix seems to have done the trick.
